////
  Copyright 2026 Quintauris GmbH
  Licensed under the Apache License, Version 2.0 (the "License").
  https://www.apache.org/licenses/LICENSE-2.0
////

include::common.adoc[]

= Meta-Model
Quintauris <www.quintauris.com> (generated {localdatetime})

== Overview

Quintauris' machine meta-model defines structure and properties of machine models employed all across the {project}.

The top-level machine meta-model is a composition of smaller, more purpose-specific meta-models. The following is a simplified, top-level description of the metamodel hierarchy:

* <<_machine>>
** (0..*) <<_import>>
** (0..*) <<_addressable>> (inline or <<_reference>>d)
*** (0..*) <<_register>>
**** (0..*) <<_field>>
** (0..*) <<_peripheral>> (inline or <<_reference>>d)
*** (0..*) <<_addressable>> (inline or <<_reference>>d)
**** (0..*) <<_register>>
***** (0..*) <<_field>>
*** (0..*) <<_parameter>>
** (0..*) <<_parameter>>

== Common Attributes

All model entities share the follwoing attributes:

name (string):: Name of the model entity
description (object):: Human-friendly description of the entity, for documentation purposes
description/content_type (string):: MIME type of `content` (`text/plain` assumed if not specified)
description/content (string):: Description content in the format specified by `content_type`

For conciseness and readability, these attributes are omitted in the following sections.

=== Constraints

ctr_comm_001:: `name` must conform to the following regular expression: `[a-zA-Z]+[0-9a-zA-Z_]*`
ctr_comm_002:: `description/content_type` must be one of `text/plain`, `text/markdown` or `text/html`

== Computed values

Attributes annotated with the 🧮 icon are strings that should be evaluated to produce an integer result.

== Machine

word_size (integer):: Default word size, in bits, of the machine (e.g. 32, 64)
imports (array):: Array of <<_import>>s, describing elements imported from other files
memory_map (array):: Array of <<_addressable>>s describing the machine's memory map
peripherals (array):: Array of <<_peripheral>>s featured by the machine
parameters (array):: Array of machine-level <<_parameter>>s

=== Constraints

ctr_mach_001:: `word_size` must be a multiple of 8
ctr_mach_002:: No two <<_import>>s can have the same name
ctr_mach_003:: No two <<_addressable>>s under `memory_map` can have the same name
ctr_mach_004:: No two <<_peripheral>>s under `peripherals` can have the same name
ctr_mach_005:: No two <<_parameters>>s under `peripherals` can have the same name

== Import

file (string):: File containing the entity to import
substitutions (object):: Key/value substitutions to apply to string values in the imported entity

=== Constraints

ctr_impr_001:: Keys within `substitutions` must be conform to the following regular expression: `[A-Z]+[0-9a-zA-Z_]*`

== Reference

reference (string):: Name assigned to <<_import>>ed entity
substitutions (object):: Key/value substitutions to apply to string values in the reference entity

=== Constraints

ctr_refr_001:: `reference` must be a `name` assignmed to an <<_import>> in the context of the reference (<<_machine>> or <<_peripheral>>)
ctr_reft_001:: Keys within `substitutions` must be conform to the following regular expression: `[A-Z]+[0-9a-zA-Z_]*`

== Addressable

base (string, 🧮):: Base address of the addressable entity
size (string, 🧮):: Size of the addressable entity, in bytes
read (boolean):: Whether the addressable entity is readable
write (boolean):: Whether the addressable entity is writable
execute (boolean):: Whether the addressable entity is executable
word_size (integer):: Default word size, in bits, of the addressable entity (assumed from enclosing <<_machine>> or <<_peripheral>> `word_size` if not defined)
default_register_class (string):: Default class for contained registers
registers (array):: Array of <<_register>>s

=== Constraints

ctr_addr_001:: `base` must evaluate to a signed integer number
ctr_addr_002:: `size` must evaluate to a signed integer number
ctr_addr_003:: `word_size` must be a multiple of 8
crt_addr_004:: `default_register_class` must be either `control_status` or `memory_mapped`
ctr_addr_005:: No two <<_register>>s can have the same name

== Register

class (string):: Register class (assumed from enclosing <<_addressable>> `default_register_class` if not defined)
width (integer):: Number of bits in the register (assumed from <<_addressable>> `word_size` if not defined)
offset (string):: Zero-based offset of the register within the memory space that contains it, in bytes
values (array) :: Array of possible <<_value>>s for the register
fields (array):: Array of register <<_field>>s within the register
indexing (object):: If defined, the register is considered an array of individual registers
indexing/lower_bound (string, 🧮):: Lower bound for indexed access
indexing/upper_bound (string, 🧮):: Upper bound for indexed access
indexing/stride (string, 🧮):: Distance between entries, in bytes

=== Constraints

crt_regs_001:: `class` must be either `control_status` or `memory_mapped`
ctr_regs_002:: `width` must be a multiple of 8
ctr_regs_003:: `offset` must evaluate to a signed integer number
ctr_regs_004:: No two <<_value>>s can have the same name
ctr_regs_005:: No two <<_fields>>s can have the same name
ctr_regs_006:: `indexing/lower_bound` must evaluate to a signed integer number equal to or higher than zero
ctr_regs_007:: `indexing/upper_bound` must evaluate to a signed integer number equal to or higher than zero
ctr_regs_008:: `indexing/stride` must evaluate to a signed integer number higher than zero

== Field

position (integer):: Zero-based offset of the field within its containing register, in bits
length (integer):: Length of the field, in bits
values (array):: Array of possible <<_value>>s for the field

=== Constraints

ctr_fild_001:: `position` must be an integer number in the range `[-(w-1), w-1]` where `w` is the value of the `width` attribute from the enclosing <<_register>>
ctr_fild_002:: `length` must be an integer number in the range `[1, w]` where `w` is the value of the `width` attribute from the enclosing <<_register>>
ctr_fild_003:: No two <<_value>>s can have the same name

== Peripheral

instance (string):: Peripheral instance name, which differentiates it from other instantiations of the same peripheral
word_size (integer):: Default word size, in bits, of the peripheral (assumed from <<_machine>> `word_size` if not defined)
addressables (array):: Array of <<_addressable>>s featured by the peripheral
parameters (array):: Array of peripheral-level <<_parameter>>s

=== Constraints

ctr_perp_001:: `instance` must conform to the following regular expression: `[a-zA-Z]+[0-9a-zA-Z_]*`
ctr_perp_002:: `word_size` must be a multiple of 8
ctr_perp_003:: No two <<_addressable>>s can have the same name
ctr_perp_004:: No two <<_parameter>>s can have the same name

== Parameter

stage (string):: One of `compile`, `link`, `run`. Determines the stage at which the parameter value is to be defined
class (string):: One of `uint8`, `uint16`, `uint32`, `uint64`, `int8`, `int16`, `int32`, `int64`. Determines the type of the parameter
value (string, 🧮):: String representation of the parameter's numerical default value

=== Constraints

ctr_parm_001:: `value` must evaluate to a signed integer number
