////
  Copyright 2026 Quintauris GmbH
  Licensed under the Apache License, Version 2.0 (the "License").
  https://www.apache.org/licenses/LICENSE-2.0
////

include::common.adoc[]

= Meta-Model
Quintauris <www.quintauris.com> (generated {localdatetime})

== Overview

Quintauris' machine meta-model defines structure and properties of machine models employed all across the {project}.

The top-level machine meta-model is a composition of smaller, more purpose-specific meta-models. The following is a simplified, top-level description of the metamodel hierarchy:

* <<_machine>>
** (0..*) <<_addressable>>
*** (0..*) <<_register>>
**** (0..*) <<_field>>
** (0..*) <<_peripheral>>
*** (0..*) <<_addressable>>
**** (0..*) <<_register>>
***** (0..*) <<_field>>
*** (0..*) <<_parameter>>
** (0..*) <<_parameter>>

== Common Attributes

All model entities share the follwoing attributes:

name:: Name of the model entity
description:: Human-friendly description of the entity, for documentation purposes

For conciseness and readability, these attributes are omitted in the following sections.

== Machine

word_size:: Default word size, in bits, of the machine (e.g. 32, 64)
memory_map:: Array of <<_addressable>>s describing the machine's memory map
peripherals:: Array of <<_peripheral>>s featured by the machine
parameters:: Array of machine-level <<_parameter>>s

== Addressable

base:: Base address of the addressable entity
size:: Size of the addressable entity, in bytes
read:: Whether the addressable entity is readable
write:: Whether the addressable entity is writable
execute:: Whether the addressable entity is executable
word_size:: Default word size, in bits, of the addressable entity (assumed from enclosing <<_machine>> or <<_peripheral>> `word_size` if not defined)
registers:: Array of <<_register>>s

== Register

class:: One of `memory_mapped`, `control_status`
width:: Number of bits in the register (assumed from <<_addressable>> `word_size` if not defined)
offset:: Zero-based offset of the register within the memory space that contains it, in bytes
values:: Array of possible <<_value>>s for the register
fields:: Array of register <<_field>>s within the register
indexing:: If defined, the register is considered an array of individual registers
indexing/lower_bound:: Lower bound for indexed access
indexing/upper_bound:: Upper bound for indexed access
indexing/stride:: Distance between entries, in bytes

== Field

position:: Zero-based offset of the field within its containing register, in bits
length:: Length of the field, in bits
values:: Array of possible <<_value>>s for the field

== Peripheral

instance:: Peripheral instance name, which differentiates it from other instantiations of the same peripheral
word_size:: Default word size, in bits, of the peripheral (assumed from <<_machine>> `word_size` if not defined)
addressables:: Array of <<_addressable>>s featured by the peripheral
parameters:: Array of peripheral-level <<_parameter>>s

== Parameter

stage:: One of `compile`, `link`, `run`. Determines the stage at which the parameter value is to be defined
class:: One of `uint8`, `uint16`, `uint32`, `uint64`, `int8`, `int16`, `int32`, `int64`. Determines the type of the parameter
value:: String representation of the parameter's numerical default value

== Value

value:: Data held by the value
