#[[
  Copyright 2026 Quintauris GmbH
  Licensed under the Apache License, Version 2.0 (the "License").
  https://www.apache.org/licenses/LICENSE-2.0
]]

add_subdirectory(compiler)
add_subdirectory(type)
add_subdirectory(hardware)
add_subdirectory(boot)
add_subdirectory(c)
add_subdirectory(uart)
add_subdirectory(test)
add_subdirectory(alloc)
add_subdirectory(spi)
